version: '3'
services:

  arcnotes:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - arcnotes-net
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://arcnotesdb:5432/postgres
      - DB_USER=postgres
      - DB_PASS=root7
    depends_on:
      - arcnotesdb
    logging:
      driver: json-file
    restart: always

  arcnotesdb:
    image: postgres:13
    networks:
      - arcnotes-net
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=root7
    volumes:
      - arcnotesdb-vol:/var/lib/postgresql/data
    restart: always

networks:
  arcnotes-net:
    driver: bridge
volumes:
  arcnotesdb-vol:
